### ISSUE TITLE
UserApp cause experiment creation to fail

### ISSUE THREAD

**Issue by zach-r-long** [activeshadow/minimega#19]
**Describe your environment**

1. phenix version in repo
2. Ubuntu 18.04
3. Go 1.14.2
4. n/a

**Describe the bug**
When calling user app that can be found in path phenix application panics due to null pointer exception

**To Reproduce**
1. Add a user app to the path
2. Create and experiment that uses that user app
3. See error in phenix log 

runtime error: invalid memory address or nil
pointer dereference
goroutine 70 [running]:
net/http.(*conn).serve.func1(0xc000127360)
        net/http/server.go:1772 +0x139
panic(0xe0e860, 0x19d5d20)
        runtime/panic.go:975 +0x3e3
phenix/app.UserApp.shellOut(0xc000402564, 0x9, 0xf317c1, 0x9, 0xc00032e3c0, 0xc00018d080, 0x812fe2)
        phenix/app/user.go:69 +0xc1
phenix/app.UserApp.Configure(0xc000402564, 0x9, 0xc00032e3c0, 0xc0000631a0, 0xc0004b6e80)
        phenix/app/user.go:30 +0x58
phenix/app.ApplyApps(0xf317c1, 0x9, 0xc00032e3c0, 0x18, 0xc00032d7a0)
        phenix/app/app.go:164 +0x1034
phenix/api/experiment.create(0xc00015c2a0, 0xc00015c2a0, 0xf30e2f)
        phenix/api/experiment/experiment.go:240 +0x308
phenix/api/experiment.Create(0xc0000a7870, 0x5, 0x5, 0x0, 0x59)
        phenix/api/experiment/experiment.go:159 +0x4cf

**Expected behavior**
Experiment creates 

Believe bug was introduced by commit 
8350a11cda4a9d4b5881de88bde85442f016ba26

**Comment by activeshadow** [comment]
@zach-r-long thanks! I saw this too while testing today. Fixed in 87524591.
