### ISSUE TITLE
Experiment does not copy all topology parameters

### ISSUE THREAD

**Issue by zach-r-long** [activeshadow/minimega#3]
**Describe your environment**

1. minimega version: latest phenix branch
2. Linux distro/version: ubuntu 18.04
3. Go compiler version: 1.14.2
4. VM types: N/A

**Describe the bug**
Specifically I noticed the issue with OSPF. Up until the experiment is configured I see all the expected configuration in phenix.bdb. After I create the experiment the ospf section seems to be reset. I believe the problem may be have to do with mapstructure.Decode.

**To Reproduce**

Use included files

1. Load topology file
bin/phenix  cfg create topo.txt

2. Load scenario file
bin/phenix cfg create sc.txt

3. cat phenix.bdb
Observe expected ospf configuration

4. Load experiment
bin/phenix cfg create exp.txt

5. cat phenix.bdb
Observe blank ospf configuration

**Expected behavior**
ospf configuration to remain unchanged by parsing experiment configuration. 

[topo.txt](https://github.com/activeshadow/minimega/files/4664442/topo.txt)
[sc.txt](https://github.com/activeshadow/minimega/files/4664443/sc.txt)
[exp.txt](https://github.com/activeshadow/minimega/files/4664444/exp.txt)

**Comment by activeshadow** [comment]
Thanks @zach-r-long! I'll look into this ASAP and get back to you.

**Comment by zach-r-long** [comment]
Fixes issue, added pull to fix template issue related to OSPF
