### ISSUE TITLE
Feature Request: New VM Status/Testing page

### ISSUE THREAD

**Issue by aherna** [activeshadow/minimega#37]
Would like a mechanism to perform and display test results from the underlying experiment. For example send all nodes a reachability test , or be able to poll running services and compare to expected results. 

Could be accomplished by reading Miniccc Responses (Lower lift probably) or interfacing with miniccc directly(would require more work), and comparing against some expected user defined responses of some kind. Minitest in minimega repo does some of this now.

The tests could be user defined app under the phenix framework .

**Comment by activeshadow** [comment]
Hi @aherna, we're actually already working on a State of Health app that does just this (and more)! I'll be pushing a new `soh-app` branch soon with the initial version. Our initial approach is simply processing miniccc responses against expected values, but I do plan on looking into direct interaction with miniccc at some point.

**Comment by aherna** [comment]
@activeshadow Cool! LMK and I will do some testing.
