### ISSUE TITLE
[apps] Startup default app needs to move Configure() code to PreStart()

### ISSUE THREAD

**Issue by glattercj** [activeshadow/minimega#41]
In the startup default app, the `Configure()` code creates interface injections e.g. for linux. If a user app adds a new VM to the topology during its own `Configure()` phase, the interface injection won't get created automatically. Moving all of the `Configure()` startup.go code into the `PreStart()` phase will fix this.

**Comment by mgaliar** [comment]
This issue is blocking my update of a few apps as well.

**Comment by activeshadow** [comment]
@mgaliar @glattercj this is now fixed (at least for the startup app).
