### ISSUE TITLE
Allow Vyatta app configuration in Scenario file

### ISSUE THREAD

**Issue by activeshadow** [activeshadow/minimega#44]
Like we do the `Startup` app, we should be able to configure the `Vyatta` app as part of the scenario file. This will allow for more generalization of the topology config in being able to move router rulesets into the scenario config.

**Comment by glattercj** [comment]
Can we rename the vyatta app to `vrouter`? Since some people might use vyos, etc...

**Comment by activeshadow** [comment]
Yup!
