### ISSUE TITLE
Benign error in booting VM image causing `phenix start` to error out

### ISSUE THREAD

**Issue by zachbthomas** [activeshadow/minimega#56]
I'm getting this error that looks like one we would ignore when spinning up some of the VMs in particular topologies. But phenix is erroring out and won't let me ignore it in v6. Is there any way to suppress errors such as this one? Are all errors treated as fatal at the moment?

```
mount: /tmp/minimega/dstImg244524753: wrong fs type, bad option, bad superblock on /dev/nbd1p1, missing codepage or helper program, or other error.
```

**Comment by activeshadow** [comment]
@zachbthomas this looks like the error one gets when trying to mount a partition for file injection that is a boot partition. Typically, when this error is received, files that are expected to be injected aren't, which would invalidate the topology. To fix this, the user usually has to specify a partition other than 1 to inject files into in the topology.

Ignoring this error may make it hard for users to figure out why files they expect to be present in VMs aren't there.

**Comment by zachbthomas** [comment]
Hmm okay, any idea how to get more information out of the error log to determine which VM has the wrong inject partition selected?

**Comment by activeshadow** [comment]
@zachbthomas that error comes directly from minimega so we'd need to update the code that shells out to the `mount` command to include the name of the VM it's prepping in the log message.
