### ISSUE TITLE
[deb] Error installing deb in docker

### ISSUE THREAD

**Issue by glattercj** [activeshadow/minimega#81]
```bash
dpkg: error processing package minimega (--configure):
 installed minimega package post-installation script subprocess returned error exit status 1
```

This occurs because of the line inside the `minimega.postinst` script: 

```bash
...
systemctl daemon-reload >/dev/null 2>&1
...
```

Since docker doesn't have systemd as the init system, the `systemctl` line fails.

**Comment by activeshadow** [comment]
@glattercj whoops... I'll figure out the best way to detect the presence of systemd as the init system.

**Comment by activeshadow** [comment]
It's possible that systemd could be installed but not currently the init system. Better option would be to check output of `/proc/1/comm` for `systemd`.
